DebugSwift/DebugSwift

.github/workflows/git-version.yml
Automate releases using Git Version to calculate the next version.  
On:
main: [major].[minor].[patch]
develop: [major].[minor].[patch]-alpha.[build]
=> Automate tags and releases

DebugSwift.podspec, DebugSwift/Sources/Features/App/Console/Helpers/LogIntercepter.swift
=> [Bugfix] Remove collect logs, that lock UI

DebugSwift.podspec, DebugSwift/Sources/Base/TabBarController.swift, DebugSwift/Sources/Features/App/App.Controller.swift, DebugSwift/Sources/Features/App/App.ViewModel.swift, DebugSwift/Sources/Features/App/Console/Helpers/LogIntercepter.swift, DebugSwift/Sources/Features/App/Crash/Detail/CrashDetailViewController.swift, DebugSwift/Sources/Features/App/Crash/Helpers/Trace.swift, DebugSwift/Sources/Features/App/Crash/Main/CrashViewController.swift, DebugSwift/Sources/Features/App/Location/Main/Location.ViewController.swift, DebugSwift/Sources/Features/Interface/Interface.Controller.swift, DebugSwift/Sources/Features/Network/Details/Network.Controller.Detail.swift, DebugSwift/Sources/Features/Network/Main/Network.Controller.swift, DebugSwift/Sources/Features/Performance/Performance.Controller.swift, DebugSwift/Sources/Features/Resources/Files/Resources.Files.Controller.swift, DebugSwift/Sources/Features/Resources/Keychain/KeychainService.swift, DebugSwift/Sources/Features/Resources/Resources.Controller.swift, DebugSwift/Sources/Helpers/Extensions/String+.swift, DebugSwift/Sources/Helpers/Extensions/UIImage+.swift, DebugSwift/Sources/Helpers/Extensions/UITableViewCell+.swift, DebugSwift/Sources/Helpers/Extensions/UIViewController+.swift
=> [Bugfix] Improve  iOS 12 And General Fixes

.github/workflows/git-version.yml, DebugSwift.podspec
Update podspec version based on next release version.
> **_NOTE:_** The Podspec version was updated based on fork tags. After merge, the version will be updated on this repo with next version. 
@MaatheusGois precisamos adicionar o token do cocoapods nas secrets do repo.
=> Update podspec version automatically

DebugSwift.podspec, DebugSwift/Sources/Base/TabBarController.swift, DebugSwift/Sources/Settings/DebugSwift.swift, Example/Example/AppDelegate.swift, Example_SwiftUI/Example_SwiftUI/Example_SwiftUIApp.swift, README.md
Added ability to add custom View Controllers into Tabbar
=> Added custom view controllers

.github/workflows/build.yml
b797cd6 fix(Action Build): New Updates ✨
=> [Bugfix] Git Actions - Build

.github/workflows/git-version.yml
c5eb1d0 fix(Xcode Version In Tag Generator): New Updates ✨
=> [Bugfix] Update Xcode version in tag manager

.github/workflows/build.yml, .github/workflows/git-version.yml
7ecd32a fix(Xcode Version In Tag Generator): Fix Tag Generation ✏️
7b4fb25 merging with develop
c5eb1d0 fix(Xcode Version In Tag Generator): New Updates ✨
=> [Bugfix] Versão Xcode No Gerador De Tags

DebugSwift/Sources/Features/Network/Details/Network.Controller.Detail.swift, DebugSwift/Sources/Features/Network/Main/Network.Controller.swift, DebugSwift/Sources/Features/Network/Main/Network.ViewModel.swift, DebugSwift/Sources/Features/Network/Views/Network.Cell.Detail.swift, Example/Example/AppDelegate.swift
- Fix Autoscrolling
- Improve networking search to (status and time)
- Fix to get all searchable
=> [Bugfix] Rolagem Automática

DebugSwift/Sources/Features/Interface/ViewDebugger/InAppViewDebugger.swift, DebugSwift/Sources/Helpers/FloatingButton/Views/FloatBallView/FloatBallView.swift, DebugSwift/Sources/Helpers/Tools/Debug.swift, DebugSwift/Sources/Helpers/Tools/ImpactFeedback.swift, DebugSwift/Sources/Helpers/Tools/UserDefaultsAccess.swift, DebugSwift/Sources/Settings/DebugSwift.swift, Example/Example/AppDelegate.swift, Example/Podfile.lock, Example/Pods/Local Podspecs/DebugSwift.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Pods/Target Support Files/DebugSwift/DebugSwift-Info.plist, Example/Pods/Target Support Files/DebugSwift/ResourceBundle-DebugSwift-DebugSwift-Info.plist
88fe045 feat(Improve Feedback): Create Option To Enable/Disable The Feedback And Remove Unused Code 🚑️
=> [Feature] Create a Option to Enable/Disable Impact Feedback

DebugSwift/Sources/Features/Network/Helpers/HTTPProtocol.swift
99ee45a feat(Fix Add Response): Fix Info ✏️
=> [Bugfix] Add response data

DebugSwift/Resources/Base.lproj/Localizable.strings, DebugSwift/Resources/en.lproj/Localizable.strings, DebugSwift/Resources/pt-BR.lproj/Localizable.strings, DebugSwift/Sources/Features/Network/Main/Network.Controller.swift, Example/Podfile.lock, Example/Pods/Local Podspecs/DebugSwift.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Target Support Files/DebugSwift/DebugSwift-Info.plist, Example/Pods/Target Support Files/DebugSwift/ResourceBundle-DebugSwift-DebugSwift-Info.plist
Add a `trailing swipe action` on cells, in order to copy current `url path`.
<image src="https://github.com/DebugSwift/DebugSwift/assets/17321857/ebff6618-5d1e-470f-a48b-1edcadb64b3b" width="300">
=> [Improvements] Add cell swipe action on requests list

.github/workflows/git-version.yml
6bf64da fix(Ci): New Updates ✨
=> [Bugfix] Ci

DebugSwift/Sources/Features/Performance/Helpers/Performance.Toolkit.swift
0ad32d4 fix(Hang In Update): Resolve Main Thread Hang 🔇
=> [Bugfix] Fix hang

DebugSwift/Resources/Base.lproj/Localizable.strings, DebugSwift/Resources/en.lproj/Localizable.strings, DebugSwift/Resources/pt-BR.lproj/Localizable.strings, DebugSwift/Sources/Features/App/Console/ConsoleViewModel.swift, DebugSwift/Sources/Features/App/CustomAction/App.CustomAction.ViewModel.swift, DebugSwift/Sources/Features/App/CustomInfo/App.CustomInfo.ViewModel.swift, DebugSwift/Sources/Features/Network/Details/Network.Controller.Detail.swift, DebugSwift/Sources/Features/Performance/Helpers/Performance.LeakDetector.swift, DebugSwift/Sources/Features/Performance/Leak/LeakViewModel.swift, DebugSwift/Sources/Features/Performance/Leak/LeaksViewModel.swift, DebugSwift/Sources/Features/Performance/Performance.Controller.swift, DebugSwift/Sources/Features/Resources/GenericList/Resources.Generic.Controller.swift, DebugSwift/Sources/Features/Resources/Keychain/Resources.Keychain.ViewModel.swift, DebugSwift/Sources/Features/Resources/UserDeafults/Resources.UserDefaults.ViewModel.swift, DebugSwift/Sources/Helpers/Managers/FileSharingManager.swift, DebugSwift/Sources/Helpers/Tools/Debug.swift, Example/Pods/Pods.xcodeproj/project.pbxproj
=> [Feature] Create Search and Share to Leaks

DebugSwift/Resources/Base.lproj/Localizable.strings, DebugSwift/Resources/en.lproj/Localizable.strings, DebugSwift/Resources/pt-BR.lproj/Localizable.strings, DebugSwift/Sources/Features/App/Console/ConsoleViewModel.swift, DebugSwift/Sources/Features/App/Console/Helpers/ConsoleOutput.swift, DebugSwift/Sources/Features/App/Console/Helpers/FileHandle+.swift, DebugSwift/Sources/Features/App/Console/Helpers/StderrCapture.swift, DebugSwift/Sources/Features/App/Console/Helpers/StdoutCapture.swift, DebugSwift/Sources/Features/App/Crash/Detail/CrashDetailViewController.swift, DebugSwift/Sources/Features/App/Crash/Detail/CrashDetailViewModel.swift, DebugSwift/Sources/Features/App/Crash/Helpers/CallStackSymbols/CallStackParser.swift, DebugSwift/Sources/Features/App/Crash/Helpers/CrashModel.swift, DebugSwift/Sources/Features/Performance/Helpers/Performance.LeakDetector.swift, DebugSwift/Sources/Features/Performance/Leak/LeaksViewModel.swift, DebugSwift/Sources/Features/Resources/GenericList/Resources.Generic.Controller.swift, DebugSwift/Sources/Helpers/Managers/FeatureHandling.swift, Example/Example.xcodeproj/project.pbxproj, Example/Example/AppDelegate.swift, Example/Example/ViewController.swift, Example/Pods/Pods.xcodeproj/project.pbxproj
8038ee0 feat(Stderr Capture): Can Take Nslog And Crash Log 🚑️
=> [Feauture] Trace Stderr

DebugSwift/Sources/Features/Performance/Helpers/Performance.LeakDetector.swift
83123d9 feat(Fix Develop Main): New Updates ✨
=> [Feature] Corrigir Desenvolver Principal

DebugSwift/Sources/Features/Network/Helpers/HTTPProtocol.swift, DebugSwift/Sources/Features/Network/Helpers/Helpers/HTTPProtocolDelegate.swift, DebugSwift/Sources/Helpers/Extensions/Data+.swift, DebugSwift/Sources/Settings/DebugSwift.Network.swift, Example/Example/Base.lproj/Main.storyboard, Example/Example/Helpers/LeakViewController.swift, Example/Example/pt-BR.lproj/Main.strings
8c2d108 fix(Content And Logs Types): Set Type Of Logs And Fix Log When Is Inputstream 🚀
=> [Bugfix] Content And Logs Types

.github/workflows/git-version.yml
54b9165 feat(0.3.7 Fix): Fix Download Artifects
=> [Release] Fix 0.3.7

DebugSwift/Sources/Features/App/Console/ConsoleViewModel.swift
8c1ea53 fix(Console Share): Fix Share Console Data
=> [Bugfix] Compartilhamento De Console

DebugSwift/Resources/Base.lproj/Localizable.strings, DebugSwift/Resources/en.lproj/Localizable.strings, DebugSwift/Sources/Features/Resources/HTTPCookies/Resources.HTTPCookies.ViewModel.swift, DebugSwift/Sources/Features/Resources/Resources.Controller.swift, Example/Podfile, Example/Podfile.lock, Example/Pods/Local Podspecs/DebugSwift.podspec.json, Example/Pods/Manifest.lock, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Pods/Target Support Files/DebugSwift/DebugSwift-Info.plist, Example/Pods/Target Support Files/DebugSwift/ResourceBundle-DebugSwift-DebugSwift-Info.plist, Example/Pods/Target Support Files/Pods-Example/Pods-Example.debug.xcconfig, Example/Pods/Target Support Files/Pods-Example/Pods-Example.release.xcconfig
I found the latest tag is in the main branch, so I submitted the code to the main branch. If you need to adjust the merged branch, please feel free to do it directly.
=> feat: support http cookies

DebugSwift/Sources/Helpers/FloatingButton/Views/FloatBallView/FloatBallView.swift, DebugSwift/Sources/Helpers/Tools/ImpactFeedback.swift, Example/Tests/Helpers/Extensions/Sources/Helpers/Extensions/UIDevice+Tests.swift, Example/Tests/Helpers/Tools/DebugTests.swift, Example/Tests/Helpers/Tools/ImpactFeedbackTests.swift, Example/Tests/Helpers/Tools/LaunchTimeTrackerTests.swift, Example/Tests/Helpers/Tools/ReachabilityTests.swift, Example/Tests/Helpers/Tools/TopUIViewTests.swift, Example/Tests/Helpers/Tools/UserDefaultsAccessTests.swift
ced7da1 feat(Add Tests To Tools): New Updates ✨
=> [Feature] Add Tests To Tools

DebugSwift/Sources/Base/BaseController.swift, DebugSwift/Sources/Base/BaseTableController.swift, DebugSwift/Sources/Base/TabBarController.swift, DebugSwift/Sources/Features/Interface/ViewDebugger/DebugSnapshotViewController.swift, DebugSwift/Sources/Features/Interface/ViewDebugger/HierarchyTableViewController.swift, DebugSwift/Sources/Features/Interface/ViewDebugger/SnapshotViewConfiguration.swift, DebugSwift/Sources/Features/Interface/ViewDebugger/VIewDebuggerViewController.swift, DebugSwift/Sources/Features/Network/Main/Network.Controller.swift, DebugSwift/Sources/Features/Performance/Helpers/Performance.Toolkit.swift, DebugSwift/Sources/Features/Performance/Performance.Controller.swift, DebugSwift/Sources/Features/Performance/Views/MenuSwitchTableViewCell.swift, DebugSwift/Sources/Features/Performance/Views/Performance.WidgetView.swift, DebugSwift/Sources/Helpers/Extensions/UINavigationController+.swift, DebugSwift/Sources/Helpers/Extensions/UIViewController+.swift, DebugSwift/Sources/Helpers/Managers/Theme.swift, Example/Example/AppDelegate.swift, Example/Tests/Features/Performance/Helpers/Performace.FPSCalculatorTests.swift, Example/Tests/Features/Performance/Helpers/Performance.LeakDetectorTests.swift, Example/Tests/Features/Performance/Helpers/Performance.MemoryWarningTests.swift, Example/Tests/Features/Performance/Helpers/Performance.ToolkitTests.swift
8db9145 feat(Fix Warnings And Layout Constraints): Add Tests ➕
8b4ffd7 feat(Fix Warnings And Layout Constraints): Fix Constraints ✏️
=> [Feature] Corrigir Avisos E Restrições De Layout

.github/workflows/danger.yml, .github/workflows/git-version.yml, Example/Tests/Features/Performance/Helpers/Performance.LeakDetectorTests.swift
081cb46 fix(Tests): Fix Tests ✏️
=> [Bugfix] Tests

DebugSwift.podspec, Example/Tests/Helpers/Extensions/UIView+Tests.swift
Close the package to new updates
=> feat(1.0.0): Update The Release 👽️

DebugSwift/Sources/Settings/DebugSwift.App.swift, Example/Example.xcodeproj/project.pbxproj, Example/Example/MapView/MapView.swift, Package.swift, README.md
This PR lowers the minimum iOS deployment target from iOS 17.0+ to iOS 14.0+ to support a wider range of devices and iOS versions, while also adding convenient static methods for presenting and removing the debugger.
- **Lowered minimum iOS version**: iOS 17.0+ → iOS 14.0+
- **Broader device support**: Now compatible with older iOS devices
- **Maintained Swift 6.0+ requirement**: Keeping modern Swift features
Added static convenience methods to `DebugSwift.App`:
```swift
@MainActor
@discardableResult
public static func presentDebugger() -> App.Type
@MainActor  
@discardableResult
public static func removeDebugger() -> App.Type
```
- **MapView refactoring**: Separated iOS 17+ specific Map implementation into `MapView17`
- **Better version compatibility**: Cleaner separation between iOS …
=> [🔄] Lower iOS Deployment Target to iOS 14.0+ and Add Static Debugger Methods

DebugSwift/Sources/Features/Resources/Database/DatabaseBrowserViewController.swift, DebugSwift/Sources/Features/Resources/Database/DatabaseBrowserViewModel.swift, DebugSwift/Sources/Features/Resources/Database/DatabaseDetailViewController.swift, DebugSwift/Sources/Features/Resources/Database/DatabaseExportViewController.swift, DebugSwift/Sources/Features/Resources/Database/DatabaseRowEditViewController.swift, DebugSwift/Sources/Features/Resources/Database/DatabaseTableViewController.swift, DebugSwift/Sources/Features/Resources/Database/Helpers/RealmManager.swift, DebugSwift/Sources/Features/Resources/Database/Helpers/SQLiteManager.swift, DebugSwift/Sources/Features/Resources/Database/SQLQueryViewController.swift, DebugSwift/Sources/Features/Resources/Resources.Controller.swift, DebugSwift/Sources/Helpers/Extensions/Data+.swift
Added a comprehensive database browser feature to DebugSwift, enabling developers to inspect and interact with SQLite databases directly within their iOS apps during debugging.
- **Database Discovery**: Automatically finds and lists all SQLite databases in the app's sandbox
- **Table Browsing**: View database schemas, tables, and their contents with column sorting
- **CRUD Operations**: Full support for creating, reading, updating, and deleting database records
- **SQL Query Editor**: Execute custom SQL queries with syntax highlighting and query history
- **JSON Data Support**: Automatically detects and displays JSON data stored in BLOB fields, with pretty-printed editing capabilities
- **Horizontal Scrolling**: Wide tables with many columns can be scrolled horizontally for better …
=> [Database Browser] Sqlite And Realm Database Reader

DebugSwift/Sources/Features/Performance/Performance.Controller.swift, DebugSwift/Sources/Features/Performance/ThreadChecker/Performance.ThreadChecker.Controller.swift, DebugSwift/Sources/Features/Performance/ThreadChecker/Performance.ThreadChecker.DetailController.swift, DebugSwift/Sources/Features/Performance/ThreadChecker/Performance.ThreadChecker.swift, DebugSwift/Sources/Features/Performance/ThreadChecker/Performance.ThreadViolationBanner.swift, DebugSwift/Sources/Settings/DebugSwift.Performance.swift, Example/Example.xcodeproj/project.pbxproj, Example/Example/ContentView.swift, Example/Example/ThreadChecker/ThreadCheckerTestView.swift, Example/Example/ThreadChecker/ThreadCheckerUIKitTestView.swift, Example/Example/ThreadCheckerTestView.swift
This PR introduces a comprehensive **Main Thread Checker** feature to DebugSwift, providing real-time detection and automatic fixing of UI operations performed off the main thread. This feature helps developers identify and resolve thread safety issues that can cause crashes and UI glitches.
---
- **Real-time monitoring** of UI operations with method swizzling
- **Three severity levels** with visual indicators:
- ⚠️ **Warning**: `setNeedsLayout`, `setNeedsDisplay`
- ❌ **Error**: `removeFromSuperview`, `viewDidLoad`  
- 🚨 **Critical**: `addSubview`, `insertSubview`
- **Comprehensive stack trace** capture with thread identification
- **Smart filtering** with configurable ignored classes
- **Three operational modes**:
- **Disabled**: Detection turned off
- **Log Only**: Record violations …
=> [🎯] Add Main Thread Checker Feature

DebugSwift/Sources/Base/FeatureBase.swift, DebugSwift/Sources/Features/App/App.Controller.swift, DebugSwift/Sources/Features/App/PushNotifications/PushNotification.Controller.swift, DebugSwift/Sources/Features/App/PushNotifications/PushNotification.Models.swift, DebugSwift/Sources/Features/App/PushNotifications/PushNotificationCreateController.swift, DebugSwift/Sources/Features/App/PushNotifications/PushNotificationHistoryController.swift, DebugSwift/Sources/Features/App/PushNotifications/PushNotificationSettingsController.swift, DebugSwift/Sources/Features/App/PushNotifications/PushNotificationSimulator.swift, DebugSwift/Sources/Features/App/PushNotifications/PushNotificationTemplatesController.swift, DebugSwift/Sources/Settings/DebugSwift.PushNotification.swift, Example/Example-Info.plist, Example/Example/ContentView.swift, Example/Example/Example.entitlements, Example/Example/ExampleApp.swift, Example/Example/ThreadChecker/ThreadCheckerTestView.swift, Example/ExampleTests/Tests/Base/FeatureBaseTests.swift, README.md
This PR introduces a comprehensive Push Notification debugging system for DebugSwift, enabling developers to simulate, test, and debug push notifications during development without requiring a server.
- **Push Notification Simulator** - Create and test notifications locally
- **Template System** - Reusable notification templates with variable substitution  
- **History Tracking** - Complete audit trail of all simulated notifications
- **Settings Management** - Configurable behavior and display options
- **Test Scenarios** - Pre-built notification flows for common use cases
- **Swift 6 Compatible** - Full concurrency support with `@Sendable` fixes
- **Modern Architecture** - Clean MVC pattern with proper separation of concerns
- **Thread-Safe** - Proper main actor isolation and async/await …
=> [Feature] Push Notifications Complete Implementation

DebugSwift/Sources/Features/Network/Details/HTTPFilterController.swift, DebugSwift/Sources/Features/Network/Details/Network.Controller.Detail.swift, DebugSwift/Sources/Features/Network/Main/Network.Controller.swift, DebugSwift/Sources/Features/Network/Main/Network.ViewModel.swift, DebugSwift/Sources/Features/Network/Models/HTTPRequestFilter.swift, DebugSwift/Sources/Features/Network/Views/Network.Cell.swift, Example/Example/ContentView.swift
=> [Feature] Improve Http Menu

DebugSwift/Resources/Base.lproj/Localizable.strings, DebugSwift/Resources/en.lproj/Localizable.strings, DebugSwift/Resources/pt-BR.lproj/Localizable.strings, DebugSwift/Sources/Features/Performance/Helpers/Performance.MemoryWarning.swift, DebugSwift/Sources/Features/Performance/Performance.Controller.swift
=> [Feature] Improve Performance Memory
